name: CI_Pizza_Planet

on:
  pull_request:
    branches:
      - main

concurrency: 
  group: CI_P_P_${{github.ref}}
  cancel-in-progress: true

jobs:
  CI_Pizza_Planet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to feature branch
        uses: actions/checkout@v3

      - name: Install dependencies
        run: make install_dependencies 

      - name: Run lint
        run: make run_lint

      - name: Run tests
        run: make run_tests